### ISSUE TITLE
duplicate images?

### ISSUE THREAD

**Issue by kevinea42** [qminor/qlens-beta#4]
qlens finds two images in nearly identical locations and with identical magnification. See this output:

`fit findimg 

# Source 0:
#src_x (arcsec)	src_y (arcsec)	n_images
-0.593807	3.416006	8	

#pos_x (arcsec)	pos_y (arcsec)	magnification
12.146539	7.782903	-1.935867
18.301817	13.734700	-0.072300
18.301807	13.734719	-0.072300
8.598727	17.241362	-0.260861
-15.753312	18.170875	3.756630
-2.905027	-7.139970	-0.417851
-3.843423	-8.789316	-1.298792
18.085010	-2.520108	8.670288`

**Comment by qminor** [comment]
This often occurs in the vicinity of critical curves--you get "phantom images" due to the way the grid cells are mapped to the source plane. It's hard to know if this is the case here without seeing the critical curves...but if it *is* the case, you should be able to fix it by increasing the number of splittings around critical curves. This is done with the command 'cc_splitlevels'. By default there are two splittings, so you can try putting the command 'cc_splitlevels 3' in your script (before the fit routine is run). With 3 or 4 splittings you can usually cure it. Does that work?

If the above doesn't work, and if you're using galaxy subgridding (around the cluster members), it's possible that a critical curve from one of the cluster members is not well resolved. You can tell this by plotting the critical curves and seeing where the phantom image is located. If it is near a critical curve from one of the cluster members, then you can try reducing the minimum cell size if you've set it in your script ('min_cellsize=...'), and possibly adding more splittings around galaxy critical curves ('galsub_cc_splitlevels=...); by default there is one splitting.

Let me know if the above options fix the issue.

**Comment by qminor** [comment]
Hi Kevin, were you able to eliminate the phantom images by increasing the number of splittings?

**Comment by kevinea42** [comment]
I’m not sure. Since getting them, I changed the model and now I have no phantom images, but it may or may not be due to increasing the cc_splitlevels. I’ll keep an eye out and if/when they happen again, I’ll try to see if I can get rid of them.

On Nov 14, 2017, at 5:57 PM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Kevin, were you able to eliminate the phantom images by increasing the number of splittings?

**Comment by qminor** [comment]
Ok...most likely increasing cc_splitlevels will solve it. I'll close this issue for now, but if it pops up again you can reopen it.
