### ISSUE TITLE
MPI error

### ISSUE THREAD

**Issue by kevinea42** [qminor/qlens-beta#5]
I was running a script that produced an MPI error partway through simulated annealing

:
```
temperature=1310.02, best_loglike=1.08302e+07       
# images: 12 vs. 14 data, chisq_pos=2.16606e+07, chisq_tot=2.16606e+07               
[Kevins-MacBook-Pro:29175] *** An error occurred in MPI_Comm_create
[Kevins-MacBook-Pro:29175] *** reported by process [184090625,0]
[Kevins-MacBook-Pro:29175] *** on communicator MPI COMMUNICATOR 3 CREATE FROM 0
[Kevins-MacBook-Pro:29175] *** MPI_ERR_INTERN: internal error
[Kevins-MacBook-Pro:29175] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[Kevins-MacBook-Pro:29175] ***    and potentially your MPI job)
```

I'll attach the script and the full session output.

[Abell_611_Richard_v9.in.txt](https://github.com/qminor/qlens-beta/files/1482808/Abell_611_Richard_v9.in.txt)
[session with MPI error.txt](https://github.com/qminor/qlens-beta/files/1482810/session.with.MPI.error.txt)

**Comment by qminor** [comment]
Hi Kevin,
No worries, I will look at this tonight or tomorrow morning at the latest
(busy day today). Did you update qlens since yesterday morning? I did fix a
couple issues with the MPI'd chi-square, so if you haven't yet, you can
give that a shot...

Quinn

**Comment by kevinea42** [comment]
Yes, I updated last night so I think I was running with the latest.


On Nov 17, 2017, at 8:07 AM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Kevin,
No worries, I will look at this tonight or tomorrow morning at the latest
(busy day today). Did you update qlens since yesterday morning? I did fix a
couple issues with the MPI'd chi-square, so if you haven't yet, you can
give that a shot...

Quinn

**Comment by kevinea42** [comment]
Also, note this message in the session text:


*WARNING*: Index didn't go through all the fit parameters (17); this likely means your current lens model does not match the lens model that was used for fitting.

Not sure why I got that. It may be a separate issue.

Kevin

On Nov 17, 2017, at 8:07 AM, qminor <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Kevin,
No worries, I will look at this tonight or tomorrow morning at the latest
(busy day today). Did you update qlens since yesterday morning? I did fix a
couple issues with the MPI'd chi-square, so if you haven't yet, you can
give that a shot...

Quinn

**Comment by qminor** [comment]
Hi Kevin,

Not sure about the MPI issue yet, but the reason you got the warning is because, when you switch to the image plane chi-square, the source point coordinates become free parameters, whereas previously they are solved for analytically. So if you do a "fit use_bestfit" after you switch to the image plane chi-square, it complains because there are more parameters compared to what you used in your previous fit. So you just have to do "fit use_bestfit" before switching to the image plane chi-square.

I doubt the above issue is the cause for the MPI error, but you could try and see if it runs better after fixing the above. When I get a chance, I will run your script on my machine and see if I can figure out what's going on.

Quinn

**Comment by qminor** [comment]
Hi Kevin,

I had a hard time reproducing this on my machine, but I think I figured out what the problem was. Can you please upgrade and try your script again? Let me know if it happens again or not.

Thanks,
Quinn
